version: '3'

services:
  my-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - ./node_modules:/app/node_modules
      - .:/app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    networks:
    - dev_network

networks:
  dev_network:
    name: dev_network