version: '3'

services:
  my-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    networks:
    - dev_network

networks:
  dev_network:
    driver: bridge